baseURL = "https://blog.zeronote.app"
title = "Zero Note: Self-destruct messages"
theme = "PaperMod"
disableKinds = ["taxonomy", "term"]

[params]
  defaultTheme = "light"
  description = "Share notes or messages without friction."
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableSpecial1stPost = true
  ShowBreadCrumbs = true
  customCSS = ["css/extended/custom.css"]
  mainSections = ["posts", "tools", "alternatives", "comparisons"]

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "https://zeronote.app"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Free tools"
    url = "/tools/"
    weight = 3

  [[menu.main]]
    name = "Alternatives"
    url = "/alternatives/"
    weight = 4

  [[menu.main]]
    name = "Comparisons"
    url = "/comparisons/"
    weight = 5