baseURL = "https://zeronote.app/blog/"
title = "Zero Note: Self-destructing shareable notes"
theme = "PaperMod"
relativeURLs = false
canonifyURLs = true

[params]
  defaultTheme = "auto"
  description = "Send notes without friction."
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableSpecial1stPost = true
  ShowBreadCrumbs = true
  customCSS = ["css/extended/custom.css"]


[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1