baseURL = "https://blog.zeronote.app"
title = "Zero Note: Self-destructible shareable notes"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  description = "Send notes without friction."
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableSpecial1stPost = true
  ShowBreadCrumbs = true
  customCSS = ["css/extended/custom.css"]

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "https://zeronote.app"
    weight = 0
    
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1